# Generated by Django 3.2 on 2021-05-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageDehazer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSNR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageID', models.CharField(max_length=200)),
                ('dcp', models.FloatField(max_length=200)),
                ('gf', models.FloatField(max_length=200)),
                ('cyclicgan', models.FloatField(max_length=200)),
                ('NovelIdea', models.FloatField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SSIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageID', models.CharField(max_length=100)),
                ('dcp', models.FloatField(max_length=200)),
                ('gf', models.FloatField(max_length=200)),
                ('cyclicgan', models.FloatField(max_length=200)),
                ('NovelIdea', models.FloatField(max_length=200)),
            ],
        ),
    ]
