# Generated by Django 3.2 on 2021-05-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageDehazer', '0002_psnr_ssim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psnr',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ssim',
            name='id',
        ),
        migrations.AlterField(
            model_name='psnr',
            name='imageID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ssim',
            name='imageID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
