# Generated by Django 3.2 on 2021-05-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageDehazer', '0003_auto_20210503_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssim',
            name='imageID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
