# Generated by Django 3.2 on 2021-05-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageDehazer', '0004_alter_ssim_imageid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psnr',
            name='NovelIdea',
            field=models.FloatField(blank=True, default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='psnr',
            name='cyclicgan',
            field=models.FloatField(blank=True, default=0, max_length=200),
        ),
    ]
