# Generated by Django 3.2 on 2021-05-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageDehazer', '0006_auto_20210507_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psnr',
            name='NovelIdea',
            field=models.FloatField(default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='psnr',
            name='cyclicgan',
            field=models.FloatField(default=0, max_length=200, null=True),
        ),
    ]
