# Generated by Django 3.2 on 2021-05-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageDehazer', '0008_auto_20210507_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='myuploadfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('myfiles', models.FileField(upload_to='myimage')),
                ('dcp', models.FileField(null=True, upload_to='myimage/dcp')),
                ('gf', models.FileField(null=True, upload_to='myimage/gf')),
                ('cyclicgan', models.FileField(null=True, upload_to='myimage/cg')),
                ('NovelIdea', models.FileField(null=True, upload_to='myimage/ni')),
                ('dcp_psnr', models.FloatField(max_length=200, null=True)),
                ('gf_psnr', models.FloatField(max_length=200, null=True)),
                ('cyclicgan_psnr', models.FloatField(default=0, max_length=200, null=True)),
                ('NovelIdea_psnr', models.FloatField(default=0, max_length=200, null=True)),
                ('dcp_ssim', models.FloatField(max_length=200, null=True)),
                ('gf_ssim', models.FloatField(max_length=200, null=True)),
                ('cyclicgan_ssim', models.FloatField(default=0, max_length=200, null=True)),
                ('NovelIdea_ssim', models.FloatField(default=0, max_length=200, null=True)),
            ],
        ),
    ]
