# Generated by Django 3.2 on 2021-05-07 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageDehazer', '0009_myuploadfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuploadfile',
            name='f_name',
        ),
    ]
