# Generated by Django 3.2 on 2021-05-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageDehazer', '0012_myuploadfile_specialid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PARAMS',
            fields=[
                ('imageID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('pdcp', models.FloatField(max_length=200)),
                ('pgf', models.FloatField(max_length=200)),
                ('pcyclicgan', models.FloatField(default=0, max_length=200, null=True)),
                ('pNovelIdea', models.FloatField(default=0, max_length=200, null=True)),
                ('sdcp', models.FloatField(max_length=200)),
                ('sgf', models.FloatField(max_length=200)),
                ('scyclicgan', models.FloatField(default=0, max_length=200, null=True)),
                ('sNovelIdea', models.FloatField(default=0, max_length=200, null=True)),
            ],
        ),
    ]
