# Generated by Django 3.2 on 2021-05-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageDehazer', '0014_auto_20210518_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuploadfile',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
